config/routes.rb
Rails.application.routes.draw do
  root to:'tops#show'
  resources :tops
  
  resources :nurutters do
    collection do
      post :confirm
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/nurutter.rb
class Nurutter < ApplicationRecord
  validates :content, presence: true, length: { in: 1..140 }   
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/nurutters_controller.rb
class NuruttersController < ApplicationController
  before_action :set_nurutter, only: [:show, :edit, :update, :destroy]

  # GET /nurutters
  # GET /nurutters.json
  def index
    @nurutters = Nurutter.all
  end

  # GET /nurutters/1
  # GET /nurutters/1.json
  def show
  end

  # GET /nurutters/new
  def new
    @nurutter = Nurutter.new
    if params[:back]
      @nurutter = Nurutter.new(nurutter_params)
    else
      @nurutter = Nurutter.new
    end
  end

  # GET /nurutters/1/edit
  def edit
  end

  # POST /nurutters
  # POST /nurutters.json
  def create
    @nurutter = Nurutter.new(nurutter_params)

    respond_to do |format|
      if @nurutter.save
        format.html { redirect_to @nurutter, notice: '投稿しました' }
        format.json { render :show, status: :created, location: @nurutter }
      else
        format.html { render :new }
        format.json { render json: @nurutter.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /nurutters/1
  # PATCH/PUT /nurutters/1.json
  def update
    
    respond_to do |format|
      if @nurutter.update(nurutter_params)
        format.html { redirect_to @nurutter, notice: '投稿しました' }
        format.json { render :show, status: :ok, location: @nurutter }
      else
        format.html { render :edit }
        format.json { render json: @nurutter.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /nurutters/1
  # DELETE /nurutters/1.json
  def destroy
    @nurutter.destroy
    respond_to do |format|
      format.html { redirect_to nurutters_url, notice: '投稿を削除しました' }
      format.json { head :no_content }
    end
  end
  
   def confirm
    @nurutter = Nurutter.new(nurutter_params)
   end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_nurutter
      @nurutter = Nurutter.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def nurutter_params
      params.require(:nurutter).permit(:content)
    end
end

app/controllers/tops_controller.rb
class TopsController < ApplicationController
  def show
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/nurutters_helper.rb
module NuruttersHelper
  def choose_new_or_edit
    if action_name == 'new' || action_name == 'confirm'
      confirm_nurutters_path
    elsif action_name == 'edit'
      nurutter_path
    end
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Sample</title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
     <header>
      <nav class="navbar navbar-default">
        <div class="container-fluid">
          <div class="navbar-header">
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
            </button>
          <a class="navbar-brand" href="/tops/show">ぬるったー</a>
          </div>
            <div id="bs-example-navbar-collapse-1" class="collapse navbar-collapse">
              <ul class="nav navbar-nav">
                  <li><%= link_to "投稿一覧", nurutters_path %></li>
                  <li><%= link_to "ぬるっとする", new_nurutter_path %></li>
             </ul>
           </div>
        </div>
      </nav>
    </header>
    
    <%= yield %>
    
    <footer>
      <p>© 2018 nurutter.com</p>
    </footer>
  </body>
</html>

app/views/nurutters/_form.html.erb
<%= form_with(model: @nurutter, local: true, url: choose_new_or_edit) do |form| %>
  <% if nurutter.errors.any? %>
    <div id="error_explanation">
      <h2><%= @nurutter.errors.count %>件のエラーがあります！</h2>
      <% nurutter.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.text_area :content, id: :nurutter_content, :maxlength=>"140" %>
  </div>

  <div class="actions">
   <button type='submit' name='action' value='send' class="btn btn-primary">ぬるっとする</button>
  </div>
<% end %>

app/views/nurutters/confirm.html.erb
<h3>以下の内容で、ぬるっとしてみる？。</h3>

<%= form_with(model: @nurutter, url: nurutters_path, local: true) do |form| %>
  <%= form.hidden_field :content %>
  <p>本文:<%= @nurutter.content %></p>
  
  <button type='submit' name='action' value='send' class="btn btn-primary">ぬるっとする</button>
  <% end %>
  
  <br>
  <%= form_with(model: @nurutter, url: new_nurutter_path, local: true, method: 'get') do |form| %>
    <%= form.hidden_field :title %>
    <%= form.hidden_field :content %>
    <%= form.submit "もどる" , :class=> "btn btn-warning" ,name: 'back' %></button>
  <% end %>
 

app/views/nurutters/edit.html.erb
<h1>編集画面</h1>

<%= render 'form', nurutter: @nurutter %>

<button type="button" class="btn btn-warning"><%= link_to 'もどる', nurutters_path %></button>

app/views/nurutters/index.html.erb
<p id="notice"><%= notice %></p>

<h1>ぬるったー</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @nurutters.each do |nurutter| %>
      <tr>
        <td><%= nurutter.content %></td>
        <td><button type="button" class="btn btn-primary"><%= link_to '見る', nurutter %></button></td>
        <td><button type="button" class="btn btn-success"><%= link_to '編集する', edit_nurutter_path(nurutter) %></button></td>
        <td><buutton type="button" class="btn btn-danger"><%= link_to '削除する', nurutter, method: :delete, data: { confirm: 'Are you sure?' } %></button></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

 

app/views/nurutters/new.html.erb
<h1>新規投稿</h1>

<%= render 'form', nurutter: @nurutter %>

app/views/nurutters/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>本文:</strong>
  
  <%= @nurutter.content %>
</p>
<br>
<button type="button" class="btn btn-success"><%= link_to '編集する', edit_nurutter_path(@nurutter) %></button>
<button type="button" class="btn btn-warning"><%= link_to '戻る', nurutters_path %></button>

app/views/tops/show.html.erb
<div class="example">
  <%= image_tag '/images/top.jpg'%>
  <p>「ぬるっと」と起きていることを見つけよう</p>
</div>